spring :
    datasource :
      url: jdbc:mysql://localhost:3306/gestionstock?createDatabaseIfNotExist=true&userSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: "gnana"
      driver-class-name: com.mysql.cj.jdbc.Driver
    ## Specify DBMS
    jpa:
      database: MYSQL
      show-sql: false  #les requetes sql
      hibernate:
        ddl-auto: update # au lancement du projet q est ce q uon veut (create ,create-drop ,update) la bdd
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
server:
    port: 8081
